### ISSUE TITLE
为什么每次show ip都提示请先使用代理后在执行这条命令

### ISSUE THREAD

**Issue by Kento-Sec** [Ggasdfg321/SmallProxyPool#1]

**Comment by Ggasdfg321** [comment]
之前代码写的逻辑问题，后面改的话太麻烦了，只能第一次使用的时候就报这个信息，后面的话我在改进一下

**Comment by lijaixin666** [comment]
每次show ip都提示请先使用代理后在执行这条命令，怎么解决

**Comment by Ggasdfg321** [comment]
你先用谷歌浏览器挂上代理（默认代理是socks5 127.0.0.1 1080），然后你在执行这条命令就可以了
