### ISSUE TITLE
win没反应

### ISSUE THREAD

**Issue by myweaven** [Ggasdfg321/SmallProxyPool#2]
![屏幕截图 2023-02-26 094109](https://user-images.githubusercontent.com/9732112/221388440-145c45eb-898e-49c2-bfa0-0ed4cf729b73.png)
如图十几分钟了都，账号配置好了的，号里也有充足的f币

**Comment by Ggasdfg321** [comment]
输入show all看看

**Comment by myweaven** [comment]
![屏幕截图 2023-02-26 105349](https://user-images.githubusercontent.com/9732112/221389680-be7731f9-9b1c-4e59-8660-f71c3a2765e5.png)
use 后再show ip显示这样，实际浏览器也没有代理成功

**Comment by Ggasdfg321** [comment]
运行了之后，出现 -> 之后，你挂代理在打开浏览器看看（记得清空缓存，谷歌浏览器按Shift+F5清空）

**Comment by myweaven** [comment]
我新开无痕窗口都没用

**Comment by myweaven** [comment]
我show ip为啥提示请先使用代理后在执行这条命令，我上面那条命令不是已经use了吗，我自己反复试了几次都不行，包括清浏览器缓存

**Comment by Ggasdfg321** [comment]
你检测一下你设置的代理是不是跟config.ini设置里的代理一样的

**Comment by Ggasdfg321** [comment]
默认设置的代理是127.0.0.1:1080

**Comment by myweaven** [comment]
可以了，感谢师傅
